
        function dashboard(){
        document.getElementById("upcomingservice").style.display="none";
            document.getElementById("newservicerequests").style.display="none";
            document.getElementById("dashboard").style.display="block";
            document.getElementById("serviceschedule").style.display="none";
            document.getElementById("servicehistory").style.display="none";
            document.getElementById("myratings").style.display="none";
                     document.getElementById("mySettings").style.display="none";

            document.getElementById("blockcustomer").style.display="none";
            document.getElementById("dashboard1").classList.add("active");
         if(document.getElementById("newservice").classList.contains("active")){
                document.getElementById("newservice").classList.remove("active");
            }
            if(document.getElementById("schedule").classList.contains("active")){
                document.getElementById("schedule").classList.remove("active");
            }
            if(document.getElementById("history").classList.contains("active")){
                document.getElementById("history").classList.remove("active");
            }
            if(document.getElementById("ratings").classList.contains("active")){
                document.getElementById("ratings").classList.remove("active");
            }
            if(document.getElementById("customer").classList.contains("active")){
                document.getElementById("customer").classList.remove("active");
            }
            }
        
        function newservice(){
            document.getElementById("newservicerequests").style.display="block";
            document.getElementById("upcomingservice").style.display="none";
            document.getElementById("dashboard").style.display="none";
            document.getElementById("serviceschedule").style.display="none";
                     document.getElementById("mySettings").style.display="none";

            document.getElementById("servicehistory").style.display="none";
            document.getElementById("myratings").style.display="none";
            document.getElementById("blockcustomer").style.display="none";
            document.getElementById("newservice").classList.add("active");
            if(document.getElementById("upcoming").classList.contains("active")){
                document.getElementById("upcoming").classList.remove("active");
            }
            if(document.getElementById("dashboard1").classList.contains("active")){
                document.getElementById("dashboard1").classList.remove("active");
            }
            if(document.getElementById("schedule").classList.contains("active")){
                document.getElementById("schedule").classList.remove("active");
            }
            if(document.getElementById("history").classList.contains("active")){
                document.getElementById("history").classList.remove("active");
            }
            if(document.getElementById("ratings").classList.contains("active")){
                document.getElementById("ratings").classList.remove("active");
            }
            if(document.getElementById("customer").classList.contains("active")){
                document.getElementById("customer").classList.remove("active");
            }
        }
        function upcoming(){
            document.getElementById("upcomingservice").style.display="block";
            document.getElementById("newservicerequests").style.display="none";
            document.getElementById("dashboard").style.display="none";
            document.getElementById("serviceschedule").style.display="none";
            document.getElementById("servicehistory").style.display="none";
            document.getElementById("myratings").style.display="none";
                     document.getElementById("mySettings").style.display="none";

            document.getElementById("blockcustomer").style.display="none";
            document.getElementById("upcoming").classList.add("active");
            if(document.getElementById("newservice").classList.contains("active")){
                document.getElementById("newservice").classList.remove("active");
            }
            if(document.getElementById("dashboard1").classList.contains("active")){
                document.getElementById("dashboard1").classList.remove("active");
            }
            if(document.getElementById("schedule").classList.contains("active")){
                document.getElementById("schedule").classList.remove("active");
            }
            if(document.getElementById("history").classList.contains("active")){
                document.getElementById("history").classList.remove("active");
            }
            if(document.getElementById("ratings").classList.contains("active")){
                document.getElementById("ratings").classList.remove("active");
            }
            if(document.getElementById("customer").classList.contains("active")){
                document.getElementById("customer").classList.remove("active");
            }
        }
       
        function schedule(){
            document.getElementById("serviceschedule").style.display="block";
            document.getElementById("upcomingservice").style.display="none";
            document.getElementById("dashboard").style.display="none";
            document.getElementById("newservicerequests").style.display="none";
            document.getElementById("servicehistory").style.display="none";
            document.getElementById("myratings").style.display="none";
                     document.getElementById("mySettings").style.display="none";

            document.getElementById("blockcustomer").style.display="none";
            document.getElementById("schedule").classList.add("active");
            if(document.getElementById("newservice").classList.contains("active")){
                document.getElementById("newservice").classList.remove("active");
            }
            if(document.getElementById("dashboard1").classList.contains("active")){
                document.getElementById("dashboard1").classList.remove("active");
            }
            if(document.getElementById("upcoming").classList.contains("active")){
                document.getElementById("upcoming").classList.remove("active");
            }
            if(document.getElementById("history").classList.contains("active")){
                document.getElementById("history").classList.remove("active");
            }
            if(document.getElementById("ratings").classList.contains("active")){
                document.getElementById("ratings").classList.remove("active");
            }
            if(document.getElementById("customer").classList.contains("active")){
                document.getElementById("customer").classList.remove("active");
            }
        }
        function history(){
            document.getElementById("servicehistory").style.display="block";
            document.getElementById("upcomingservice").style.display="none";
            document.getElementById("dashboard").style.display="none";
            document.getElementById("newservicerequests").style.display="none";
            document.getElementById("serviceschedule").style.display="none";
            document.getElementById("myratings").style.display="none";
                     document.getElementById("mySettings").style.display="none";

            document.getElementById("blockcustomer").style.display="none";
            document.getElementById("history").classList.add("active");
            if(document.getElementById("newservice").classList.contains("active")){
                document.getElementById("newservice").classList.remove("active");
            }
            if(document.getElementById("dashboard1").classList.contains("active")){
                document.getElementById("dashboard1").classList.remove("active");
            }
            if(document.getElementById("upcoming").classList.contains("active")){
                document.getElementById("upcoming").classList.remove("active");
            }
            if(document.getElementById("schedule").classList.contains("active")){
                document.getElementById("schedule").classList.remove("active");
            }
            if(document.getElementById("ratings").classList.contains("active")){
                document.getElementById("ratings").classList.remove("active");
            }
            if(document.getElementById("customer").classList.contains("active")){
                document.getElementById("customer").classList.remove("active");
            }
        }
        function ratings(){
            document.getElementById("myratings").style.display="block";
            document.getElementById("upcomingservice").style.display="none";
            document.getElementById("dashboard").style.display="none";
             document.getElementById("mySettings").style.display="none";
                document.getElementById("newservicerequests").style.display="none";
            document.getElementById("serviceschedule").style.display="none";
            document.getElementById("servicehistory").style.display="none";
            document.getElementById("blockcustomer").style.display="none";
            document.getElementById("ratings").classList.add("active");
            if(document.getElementById("newservice").classList.contains("active")){
                document.getElementById("newservice").classList.remove("active");
            }
            if(document.getElementById("dashboard1").classList.contains("active")){
                document.getElementById("dashboard1").classList.remove("active");
            }
            if(document.getElementById("upcoming").classList.contains("active")){
                document.getElementById("upcoming").classList.remove("active");
            }
            if(document.getElementById("schedule").classList.contains("active")){
                document.getElementById("schedule").classList.remove("active");
            }
            if(document.getElementById("history").classList.contains("active")){
                document.getElementById("history").classList.remove("active");
            }
            if(document.getElementById("customer").classList.contains("active")){
                document.getElementById("customer").classList.remove("active");
            }
        }
        function blockcustomer(){
            document.getElementById("blockcustomer").style.display="block";
            document.getElementById("upcomingservice").style.display="none";
            document.getElementById("mySettings").style.display="none";
            document.getElementById("dashboard").style.display="none";
            document.getElementById("newservicerequests").style.display="none";
            document.getElementById("serviceschedule").style.display="none";
            document.getElementById("servicehistory").style.display="none";
            document.getElementById("myratings").style.display="none";
            document.getElementById("customer").classList.add("active");
            if(document.getElementById("newservice").classList.contains("active")){
                document.getElementById("newservice").classList.remove("active");
            }
            if(document.getElementById("dashboard1").classList.contains("active")){
                document.getElementById("dashboard1").classList.remove("active");
            }
            if(document.getElementById("upcoming").classList.contains("active")){
                document.getElementById("upcoming").classList.remove("active");
            }
            if(document.getElementById("schedule").classList.contains("active")){
                document.getElementById("schedule").classList.remove("active");
            }
            if(document.getElementById("history").classList.contains("active")){
                document.getElementById("history").classList.remove("active");
            }
            if(document.getElementById("ratings").classList.contains("active")){
                document.getElementById("ratings").classList.remove("active");
            }
        }
      
      function mySettings(){
     document.getElementById("mySettings").style.display="block";
     document.getElementById("upcomingservice").style.display="none";
    document.getElementById("newservicerequests").style.display="none";
    document.getElementById("dashboard").style.display="none";
            document.getElementById("serviceschedule").style.display="none";
            document.getElementById("servicehistory").style.display="none";
            document.getElementById("myratings").style.display="none";
            document.getElementById("blockcustomer").style.display="none";
             if(document.getElementById("newservice").classList.contains("active")){
                document.getElementById("newservice").classList.remove("active");
            }
            if(document.getElementById("upcoming").classList.contains("active")){
                document.getElementById("upcoming").classList.remove("active");
            }
            if(document.getElementById("schedule").classList.contains("active")){
                document.getElementById("schedule").classList.remove("active");
            }
            if(document.getElementById("history").classList.contains("active")){
                document.getElementById("history").classList.remove("active");
            }
            if(document.getElementById("ratings").classList.contains("active")){
                document.getElementById("ratings").classList.remove("active");
            }
            if(document.getElementById("customer").classList.contains("active")){
                document.getElementById("customer").classList.remove("active");
            }
            if(document.getElementById("dashboard1").classList.contains("active")){
                document.getElementById("dashboard1").classList.remove("active");
            }

}      

